name: Build Windows Wheel (Python 3.13)

on:
  workflow_dispatch:  # 手动触发

jobs:
  windows-wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        cibw_arch: [x86, AMD64, ARM64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout extra test images
        uses: actions/checkout@v4
        with:
          repository: python-pillow/test-images
          path: Tests\test-images

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install cibuildwheel
        run: python -m pip install -r .ci/requirements-cibw.txt

      - name: Prepare for build
        run: |
          choco install nasm --no-progress
          echo "C:\Program Files\NASM" >> $env:GITHUB_PATH
          xcopy /S /Y Tests\test-images\* Tests\images
          & python.exe winbuild\build_prepare.py -v --no-imagequant --architecture=${{ matrix.cibw_arch }}
        shell: pwsh

      - name: Build wheel
        run: |
          setlocal EnableDelayedExpansion
          call winbuild\build\build_env.cmd
          %pythonLocation%\python.exe -m cibuildwheel . --output-dir wheelhouse
        env:
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_BEFORE_ALL: "{package}\\winbuild\\build\\build_dep_all.cmd"
          CIBW_CACHE_PATH: "C:\\cibw"
          CIBW_SKIP: pp38-*
          CIBW_TEST_SKIP: "*-win_arm64"
        shell: cmd

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels-${{ matrix.cibw_arch }}
          path: ./wheelhouse/*.whl

      - name: Upload fribidi.dll
        uses: actions/upload-artifact@v4
        with:
          name: fribidi-windows-${{ matrix.cibw_arch }}
          path: winbuild\build\bin\fribidi*
